apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-java-login-app.fullname" . }}
  labels:
    {{- include "helm-java-login-app.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "helm-java-login-app.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "helm-java-login-app.name" . }}

    spec:
      containers:
        - name: java-login-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
