apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-java-login-app.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "helm-java-login-app.name" . }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
